# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    # id: 页面中高亮的 menu_id
    # theme: 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
    # icon: 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
    # title: 标题
    # url: # 点击跳转到哪，支持相对路径和绝对路径
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /blog/
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 笔记
      url: /notes/
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

######## Sidebar ########
sidebar:
  logo:
    avatar: "[config.avatar](/)" # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: "[config.title](/)"
  # menu:
  #   home: "[btn.home](/)"
  #   post: "[btn.blog](/blog/)"
  #   wiki: "[btn.wiki](/wiki/)"
  #   notes: "[btn.notes](/notes/)"
  #   friends: "[btn.friends](/friends/)"
  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: [search, welcome, recent, timeline] # for home
    # 博客索引页
    blog_index: [search_blog, recent, timeline] # for categories/tags/archives
    # 文档索引页
    wiki_index: [search_docs, recent, timeline] # for wiki
    # 其它（404）
    others: [search, welcome, recent, timeline] # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: [toc, ghrepo, search, ghissues] # for pages using 'layout:post'
    # 文档内页
    wiki: [search, ghrepo, toc, ghissues, related] # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: [welcome, toc, search] # for custom pages using 'layout:page'

######## Article ########
article:
  # 文章许可协议
  license: "本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 许可协议，转载请注明出处。"
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面图片？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    "探索号": "#f44336"
  # 分享
  share: [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 5

######## Comments ########
comments:
  service: twikoo # beaudar, utterances, twikoo, waline
  # Twikoo
  # https://twikoo.js.org/
  twikoo:
    js: https://unpkg.com/twikoo@1.6.38 # 建议锁定版本
    envId: https://twikoo.moieo.cn # vercel函数

######## Footer ########
footer:
  since: "2022-2025"
  social:
    - icon: '<img src="/static/github.svg" alt="Github" />'
      url: https://github.com/moieo
      title: "GitHub (@Moieo)"
    - icon: '<img src="/static/gitee.svg" alt="Gitee" />'
      url: https://gitee.com/moieo
      title: "Gitee (@Moieo)"
    - icon: '<img src="/static/gitlab.svg" alt="GitLab" />'
      url: https://gitlab.com/moieo
      title: "GitLab (@Moieo)"
    - icon: '<img src="/static/email.svg" alt="E-Mail" />'
      url: mailto:moe@moieo.cn
      title: "向我发送邮件"
  # largesocial:
  sitemap:
    "主页":
      - "[关于](/)"
      - "[联系我](/contact-me/)"
    "博客":
      - "[近期发布](/blog/)"
      - "[分类](/categories/)"
      - "[标签](/tags/)"
      - "[归档](/archives/)"
      - "[Wiki](/wiki/)"
    "社交":
      - "[友链](/friends/)"
      - "[微博](https://weibo.com/moieo)"
    "联系我":
      - "[联系我 (详细信息页)](/about/)"
      - "[E-mail](mailto:moe@moieo.cn)"
      - "[GitHub](https://github.com/moieo)"
      - "[GitLab](https://gitlab.com/moieo)"
      - "[Gitee](https://gitee.com/moieo)"
  content: |
    本站由 [Hexo](https://hexo.io/) & [Hexo Theme Stellar](https://xaoxuu.com/wiki/stellar/) 强力驱动
    Copyright © 2020-2024 [@Moieo](https://moieo.cn) 版权所有
    [萌ICP备20242224号](https://icp.gov.moe/?keyword=20242224)
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 许可协议，转载请注明出处。
    <div id="established-time"></div>
    <script id="LA-DATA-WIDGET" crossorigin="anonymous" charset="UTF-8" src="https://v6-widget.51.la/v6/KKsmYv7pY2PCd0iu/quote.js?theme=#000000,#333333,#999999,#333333,#FFFFFF,#1690FF,12&f=12&display=0,0,1,1,1,1,0,1"></script>
#[赣ICP备2022010558号](http://beian.miit.gov.cn/)
# <img alt="" width="12px" height="12px" src="https://g.csdnimg.cn/common/csdn-footer/images/badge.png" />
######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true
  emoji:
    default: https://cdn.statically.io/gh/cdn-x/emoji/qq/${name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/${name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoji/qq/${name}.gif
    aru: https://gcore.jsdelivr.net/gh/cdn-x/emoji/aru-l/${name}.gif
    tieba: https://gcore.jsdelivr.net/gh/cdn-x/emoji/tieba/${name}.png
    blobcat: https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs/${name}.png

style:
  font-size: 16px
  font-family:
    # body: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, sans-serif'
    # code: '"ProFont For Powerline", "Smiley Sans", "LXGW WenKai Screen", "Apple Color Emoji", "Source Han Serif", system-ui, -apple-system, monospace, sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
